[package]
name = "throughput-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
bertha = { path = "../bertha" }
kvstore = { path = "../kvstore" }
dpdk-direct = { path = "../dpdk-direct" }
dpdk-wrapper = { path = "../dpdk-direct/dpdk-wrapper" }
shenango-chunnel = { path = "../shenango-chunnel" }
shenango = { path = "../shenango-chunnel/caladan/bindings/rust" }
shenango-bertha = { path = "../shenango-bertha" }
flume = "0.10"
futures-util = "0.3"
tokio = { version = "1", features = ["rt", "rt-multi-thread"] }
color-eyre = "0.6"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-error = "0.2"
tracing-futures = "0.2"
structopt = "0.3"
rand = "0.8"
