[package]
name = "static_test"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1"
burrito-addr = {path = "../burrito-addr"}
burrito-ctl = {path = "../burrito-ctl"}
criterion-stats = "=0.3.0"
failure = "0.1"
hyper = {version = "0.13", features = ["stream"]}
structopt = "0.3"
tokio = {version = "0.2", features = ["full"]}
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"
tracing-timing  = "0.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "unix_ping"
harness = false
