[package]
name = "burrito"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = {git = "https://github.com/akshayknarayan/bollard", branch = "std-future" }
bytes = "0.4"
failure = "0.1"
futures-util-preview = "0.3.0-alpha.19"
hyper = {version = "0.13.0-alpha.4", features = ["unstable-stream"]}
hyper-unix-connector = "0.1.0"
prost = "0.5"
prost-derive = "0.5"
rand = "0.7"
structopt = "0.3"
slog = "2"
slog-term = "2"
regex = "1"
lazy_static = "1"
slog-async = "2"
tokio = "=0.2.0-alpha.6"
tonic = "0.1.0-alpha.3"

[build-dependencies]
tonic-build = "0.1.0-alpha.3"
