[workspace]

members = [
    "burrito-addr",
    "burrito-route-ctl",
    "burrito-flatbuf",
    "burrito-util",
    "kvstore",
    "kvstore-ycsb",
    "rpcbench",
    "static-test",
    "xdp-shard",
]

[profile.release]
debug = true
