[workspace]

members = [
    "burrito-addr",
    "burrito-discovery-ctl",
    "burrito-localname-ctl",
    "burrito-shard-ctl",
    "burrito-flatbuf",
    "burrito-util",
    "kvstore",
    "kvstore-ycsb",
    "rpcbench",
    "xdp-shard",
]

[profile.release]
debug = true
