[workspace]

members = [
    "bertha",
    "burrito-localname-ctl",
    "burrito-shard-ctl",
    "kvstore",
    "kvstore-ycsb",
    "rpcbench",
    "shenango-chunnel",
    "test-util",
    "xdp-shard",
    "az-queues",
    "gcp-pubsub",
    "sqs",
    "queue-steer",
    "round-order",
]

[profile.release]
debug = true
#lto = true

[profile.release.package.kvstore]
debug = true
