[workspace]

members = [
    "bertha",
    "burrito-shard-ctl",
    "burrito-util",
    "kvstore",
    "kvstore-ycsb",
#    "rpcbench",
    "shenango-chunnel",
    "test-util",
    "xdp-shard",
]

[profile.release]
debug = true
lto = true

[profile.release.package.kvstore]
debug = true
