[package]
name = "bertha"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3"
tokio = { version = "0.2", features = ["sync", "time", "macros", "tcp", "stream", "udp"] }
color-eyre = "0.5"
eyre = "0.6"
tracing = { version = "0.1", features = ["release_max_level_debug"] }
tracing-futures = "0.2"
rand = "0.7"
serde = "1"
bincode = "1"
pin-project = "0.4"

[dev-dependencies]
tokio = { version = "0.2", features = ["rt-core"] }
tracing-subscriber = "0.2"
serde = { version = "1", features = ["derive"] }
