[package]
name = "bertha"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["sync", "time", "macros", "tcp", "stream", "udp", "uds"] }
color-eyre = "0.5"
futures-util = "0.3"
tracing = { version = "0.1" }
tracing-futures = "0.2"
rand = "0.7"
serde = "1"
bincode = "1"
pin-project = "1"
paste = "1"
lazy_static = "1.4"
dashmap = "3"
ahash = "0.5"
hdrhistogram = "7"

[dev-dependencies]
tokio = { version = "0.2", features = ["rt-core", "rt-threaded"] }
tracing-subscriber = "0.2"
tracing-error = "0.1"
serde = { version = "1", features = ["derive"] }
