[package]
name = "test-util"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
slog = "2"
slog-term = "2"
tokio = { version = "0.2", features = ["sync", "rt-core", "uds", "time", "rt-threaded"] }
redis = "0.15"
