[package]
name = "sqs"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

[dependencies]
bertha = { path = "../bertha" }
tokio = { version = "1", features = [] }
color-eyre = "=0.5.7"
tracing = { version = "0.1" }
tracing-futures = "0.2"
futures-util = "0.3"
rusoto_core = "0.47"
rusoto_sqs = "0.47"
rusoto_credential = "0.47"
rand = "0.7"
base64 = "0.13"
serde = "1"

[dev-dependencies]
tracing-subscriber = "0.2"
tracing-error = "0.1"
