[package]
name = "sqs"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2021"

[dependencies]
bertha = { path = "../bertha" }
tokio = { version = "1", features = [] }
color-eyre = "0.6"
tracing = { version = "0.1" }
tracing-futures = "0.2"
futures-util = "0.3"
rusoto_core = "0.48"
rusoto_sqs = "0.48"
rusoto_credential = "0.48"
rand = "0.8"
base64 = "0.21"
serde = "1"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-error = "0.2"
