[package]
name = "bertha-attr"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["full", "extra-traits", "parsing", "printing"] }
quote = "1"
serde = "1"
bincode = "1"
