apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  hostNetwork: true
  containers:
  - name: redis
    image: redis:latest
    ports:
    - containerPort: 6379
      name: redis-port
