[package]
name = "burrito-shard-ctl"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-bincode = "0.5"
bincode = "1"
ctrlc = "3.1.3"
futures-util = "0.3"
serde = "1"
structopt = "0.3"
redis = "0.15"
tower-service = "0.3"
tokio = { version = "0.2", features = ["sync", "rt-core"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"
xdp-shard = { path = "../xdp-shard" }
