[package]
name = "burrito-shard-ctl"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
ebpf = ["xdp-shard/ebpf"]

[dependencies]
burrito-discovery-ctl = { path = "../burrito-discovery-ctl" }
bertha = { path = "../bertha" }
xdp-shard = { path = "../xdp-shard", optional = true }
eyre = "0.6"
bincode = "1"
tracing = "0.1"
tracing-futures = "0.2"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["sync", "time"] }
redis = { version = "0.15" }

[dev-dependencies]
test-util = { path = "../test-util" }
tokio = { version = "0.2", features = ["rt-core"] }
tracing-subscriber = "0.2"
