[package]
name = "burrito-shard-ctl"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
ebpf = ["xdp-shard/ebpf"]
bin = ["structopt", "ctrlc", "redis", "tower-service", "tracing-subscriber", "tokio/rt-threaded", "tokio/macros", "tokio/time"]
ebpf-bin = ["bin", "ebpf"]

[dependencies]
anyhow = "1"
burrito-discovery-ctl = { path = "../burrito-discovery-ctl" }
async-bincode = "0.5"
bincode = "1"
futures-util = { version = "0.3", features = ["sink"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["sync", "rt-core", "uds", "time"] }
tracing = "0.1"
ctrlc = { version = "3.1.3", optional = true }
redis = { version = "0.15", optional = true }
structopt = { version = "0.3", optional = true }
tower-service = { version = "0.3", optional = true }
tracing-subscriber = { version = "0.2", optional = true }
xdp-shard = { path = "../xdp-shard", optional = true }

[dev-dependencies]
burrito-shard-ctl = { path = ".", features = ["bin"] }
slog = "2"
test-util = { path = "../test-util" }

[[bin]]
name = "burrito-shard"
required-features = ["bin"]
