[package]
name = "kvstore-ycsb"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burrito-addr = {path = "../burrito-addr"}
burrito-ctl = {path = "../burrito-ctl"}
futures-util = "0.3"
hyper-unix-connector = "0.1.4"
hyper = {version = "0.13", features = ["stream"]}
incoming = "0.1"
kvstore = {path = "../kvstore"}
slog = "2"
slog-term = "2"
structopt = "0.3"
tokio = {version = "0.2.11", features = ["full"]}
async-timer = "0.7"
tower-buffer = "0.3"
tower-service = "0.3"
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"
tracing-timing  = "=0.3.0"
ahash = "0.3"

[dev-dependencies]
criterion = "0.3"
bincode = "1"

[[bench]]
name = "ycsb"
harness = false
