[package]
name = "queue-steer"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

[dependencies]
sqs = { path = "../sqs" }
gcp-pubsub = { path = "../gcp-pubsub" }
az-queues = { path = "../az-queues" }
bertha = { path = "../bertha" }
color-eyre = "=0.5.7"
tokio = { version = "1", features = ["macros"] }
