[package]
name = "burrito-addr"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = {version = "0.13", features = ["stream"]}
tokio = "0.2"
failure = "0.1"
tonic = "0.1"
prost = "0.6"
prost-derive = "0.6"
bytes = "0.4"
pin-project = "0.4"
hyper-unix-connector = "0.1.4"
futures-util = "0.3"
hex = "0.4"
burrito-ctl = {path = "../burrito-ctl"}
slog = "2"
slog-term = "2"

[build-dependencies]
tonic-build = "0.1"
