[package]
name = "ycsb-shenango"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burrito-shard-ctl = {path = "../burrito-shard-ctl"}
burrito-discovery-ctl = {path = "../burrito-discovery-ctl"}
kvstore = {path = "../kvstore"}
kvstore-ycsb = {path = "../kvstore-ycsb"}
tokio = {version = "0.2.20", features = ["full"]}
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"
tracing-timing  = "=0.3.0"
rand = "0.7"
rand_distr = "0.2"
bincode = "1"
structopt = "0.3"
shenango = { path = "../../shenango/bindings/rust" }
crossbeam = "0.7"
anyhow = "1"
chashmap = "2"
