[machines]
server = { access = "127.0.0.1", alt = "192.168.1.6", exp = "10.1.1.6" }
clients = [
    { access = "192.168.1.3", exp = "10.1.1.3" },
    { access = "192.168.1.4", exp = "10.1.1.4" },
    { access = "192.168.1.5", exp = "10.1.1.5" },
]

[exp]
wrk = ["./kvstore-ycsb/ycsbc-mock/wrkloadbunf1-4.access"]
datapath = ['shenango_channel', 'dpdkmulti', 'dpdkthread', 'kernel']
load = [10000, 20000, 40000, 60000, 80000, 100000, 120000, 140000, 160000, 180000, 200000]
poisson-arrivals = [true]
shardtype = ["client"]
shards = [4]
