[machines]
server = { access = "127.0.0.1", alt = "192.168.1.2", exp = "10.1.1.2" }
clients = [
    { access = "192.168.1.5", exp = "10.1.1.5" },
    { access = "192.168.1.6", exp = "10.1.1.6" },
    { access = "192.168.1.7", exp = "10.1.1.7" },
    { access = "192.168.1.8", exp = "10.1.1.8" },
    { access = "192.168.1.9", exp = "10.1.1.9" },
]

[exp]
wrk = ["./kvstore-ycsb/ycsbc-mock/wrkloadbunf1-4.access"]
datapath = ['kernel', 'shenango_channel', 'dpdkmulti', 'dpdkthread']
load = [10000, 20000, 40000, 60000, 80000, 100000, 120000, 140000, 160000, 180000, 200000]
poisson-arrivals = [true]
shardtype = ["client"]
shards = [4]
