[machines]
server = [
    { access = "128.110.218.171", user = "akshayn", alt = "128.110.218.171", exp = "10.10.1.2", mac = "9c:dc:71:56:af:45" } # node-0
    { access = "128.110.218.86", user = "akshayn", alt = "128.110.218.86", exp = "10.10.1.3", mac = "9c:dc:71:5e:2f:61" } # node-2
]
clients = [
    #{ access = "128.110.218.134", user = "akshayn", alt = "128.110.218.134", exp = "10.10.1.1", mac = "9c:dc:71:49:a8:a1" }, # node-1
    { access = "128.110.218.181", user = "akshayn", alt = "128.110.218.181", exp = "10.10.1.4", mac = "9c:dc:71:4b:63:21" }, # node-3
]

[cfg]
lcores = "0,1,2,3,4,5,6,7,8,9"

[cfg.client]
num-threads = 10

[cfg.server]
num-threads = 10

[exp]
wrk = ["./kvstore-ycsb/ycsbc-mock/workloadb-8.access"]
datapath = ['dpdkmulti']
load = [10000, 20000, 40000, 60000, 80000, 100000, 120000]
poisson-arrivals = [true]
shardtype = ["server"]
shards = [8]
negotiation = [true]
optimization = [true, false]
iters = 3
