[machines]
server = { access = "127.0.0.1", alt = "192.168.1.2", exp = "10.1.1.2" }
clients = [
    { access = "192.168.1.6", exp = "10.1.1.6" },
]

[exp]
iters = 5
msg_size = [0, 128, 1024]
datapath = ['dpdk', 'shenango']
#bertha = [True, False]
