[machines]
server = { access = "128.110.218.105", user = "akshayn", alt = "128.110.218.105", exp = "10.10.1.2", mac = "9c:dc:71:5d:01:91" } # node-0
clients = [
    { access = "128.110.218.109", user = "akshayn", alt = "128.110.218.109", exp = "10.10.1.1", mac = "9c:dc:71:5b:42:91" }, # node-1
]

[cfg]
lcores = "0,1,2,3,4,5,6,7,8,9"
#lcores = "1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63"

[cfg.client]
num-threads = 10

[cfg.server]
num-threads = 10

[exp]
num_clients = [10]
file_size = [5000000000]
packet_size = [64, 128, 256, 512, 1024, 1460]
#datapath = ['kernel', 'dpdkinline', 'shenango', 'shenangort']
datapath = ['dpdkinline', 'shenangort']
iters = 5
bertha = ['raw', 'full:0', 'full:1', 'full:2', 'full:3', 'full:4', 'full:5']
