[machines]
server = { access = "127.0.0.1", user = "akshayn", alt = "18.26.5.6", exp = "10.1.1.6", mac = "f4:52:14:76:98:a0" } # pd6
clients = [
    { access = "18.26.5.5", user = "akshayn", alt = "18.25.5.5", exp = "10.1.1.5", mac = "f4:52:14:76:98:30" }, # pd5
]

[cfg]
lcores = "0,1,2,3,4"

[cfg.client]
num-threads = 4

[cfg.server]
num-threads = 4

[exp]
num_clients = [4]
file_size = [5000000000]
packet_size = [64, 128, 256, 512, 1024, 1460]
datapath = ['kernel']
iters = 5
bertha = ['raw', 'full:0', 'full:1', 'full:2', 'full:3', 'full:4', 'full:5']
tcp = [true]
