[machines]
server = { access = "192.168.1.6", exp = "10.1.1.6" }
clients = [
  { access = "127.0.0.1", exp = "10.1.1.2" }
]

[exp]
num_clients = [1,2,4,8,16,32,64,128]
file_size = [50000000]
datapath = ['dpdk', 'shenango', 'kernel']
iters = 5
bertha = [true, false]
