[package]
name = "tcp"
version = "0.1.0"
edition = "2021"

[dependencies]
bertha = { path = "../bertha" }
tokio = { version = "1", features = ["net"] }
tokio-stream = { version = "0.1", features = ["net"] }
socket2 = "0.4"
color-eyre = "0.6"
tracing = "0.1"
tracing-futures = "0.2"
futures-util = "0.3"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-error = "0.2"
tokio = { version = "1", features = ["rt"] }
