[package]
name = "tcp"
version = "0.1.0"
edition = "2021"

[dependencies]
bertha = { path = "../bertha" }
tokio = { version = "1", features = ["net"] }
tokio-stream = { version = "0.1", features = ["net"] }
color-eyre = "0.6"
tracing = "0.1"
tracing-futures = "0.2"
futures-util = "0.3"

[dev-dependencies]
tracing-subscriber = "0.2"
tracing-error = "0.1"
tokio = { version = "1", features = ["rt"] }
