[package]
name = "rpcbench"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4"
failure = "0.1"
rand = "0.7"
rand_distr = "0.2"
prost = "0.5"
prost-derive = "0.5"
tokio = "=0.2.0-alpha.6"
tower = "=0.3.0-alpha.2"
tonic = "=0.1.0-alpha.5"
structopt = "0.3"

[build-dependencies]
tonic-build = "=0.1.0-alpha.5"
