[package]
name = "rpcbench"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burrito-addr = {path = "../burrito-addr"}
burrito-util = {path = "../burrito-util"}
bytes = "0.4"
criterion = "0.3"
failure = "0.1"
http-body = "0.3"
hyper-unix-connector = "0.1"
hyper = {version = "0.13", features = ["stream"]}
prost = "0.6"
prost-derive = "0.6"
rand = "0.7"
rand_distr = "0.2"
serde = "1"
slog = "2"
slog-term = "2"
structopt = "0.3"
tokio = {version = "0.2.11", features = ["full"]}
tonic = "0.1"
tower = "0.3"
tower-make = "0.3"
tracing = "0.1"
tracing-futures = "0.2"
tracing-timing  = { version = "0.4", features = ["layer"] }
tracing-subscriber = "0.2.5"
bincode = "1"
futures-util = "0.3"

[dev-dependencies]
redis = "0.15"
burrito-localname-ctl = { path = "../burrito-localname-ctl", features = ["ctl"] }
burrito-discovery-ctl = { path = "../burrito-discovery-ctl", features = ["ctl"] }
test-util = { path = "../test-util" }

[build-dependencies]
tonic-build = "0.1"
