[package]
name = "rpcbench"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4"
failure = "0.1"
rand = "0.7"
rand_distr = "0.2"
prost = "0.6"
prost-derive = "0.6"
tokio = "0.2"
tower = "0.3"
tower-make = "0.3"
tonic = "0.1"
structopt = "0.3"
burrito-addr = {path = "../burrito-addr"}
hyper = {version = "0.13", features = ["stream"]}
burrito-ctl = {path = "../burrito-ctl"}
slog = {version = "2", features = ["max_level_trace"]}
slog-term = "2"
hyper-unix-connector = { version = "0.1.3", optional = true }

[dev-dependencies]
hyper-unix-connector = "0.1.3"

[build-dependencies]
tonic-build = "0.1"

[features]
unix-connector = ["hyper-unix-connector"]

[[bin]]
name = "client"
required-features = ["unix-connector"]
