[package]
name = "rpcbench"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4"
failure = "0.1"
rand = "0.7"
rand_distr = "0.2"
prost = "0.5"
prost-derive = "0.5"
tokio = "=0.2.0-alpha.6"
tower = "=0.3.0-alpha.2"
tower-make = "=0.3.0-alpha.2a"
#tonic = "=0.1.0-alpha.5"
tonic = {path = "../../tonic/tonic"}
structopt = "0.3"
burrito-addr = {path = "../burrito-addr"}
hyper = {version = "=0.13.0-alpha.4", features = ["unstable-stream"]}
burrito-ctl = {path = "../burrito-ctl"}
slog = {version = "2", features = ["max_level_trace"]}
slog-term = "2"
hyper-unix-connector = { version = "0.1.3", optional = true }

[dev-dependencies]
hyper-unix-connector = "0.1.3"

[build-dependencies]
#tonic-build = "=0.1.0-alpha.5"
tonic-build = {path = "../../tonic/tonic-build"}

[features]
unix-connector = ["hyper-unix-connector"]

[[bin]]
name = "client"
required-features = ["unix-connector"]
