name: Rust

on:
  push:
    branches: [ master, bertha ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo check --verbose --all-targets
    - name: Run tests
      run: cargo test --verbose -- bertha
