[package]
name = "kvstore"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

[dependencies]
bertha = { path = "../bertha" }
burrito-shard-ctl = {path = "../burrito-shard-ctl"}
burrito-util = {path = "../burrito-util"}
bincode = "1"
ctrlc = "3"
serde  = { version = "1", features = ["derive"]}
rand = "0.7"
async-bincode = "0.5"
tokio-tower = "=0.3.5"
tower-service = "0.3"
futures-util = "0.3"
tokio = {version = "0.2.11", features = ["full"]}
slog = "2"
slog-term = "2"
structopt = "0.3"
tracing = "0.1"
tracing-futures = "0.2"
tracing-timing  = "0.3"
tracing-subscriber = "0.2"
hyper = {version = "0.13", features = ["stream"]}
hyper-unix-connector = "0.1"
hashbrown = "0.7"
tower-buffer = "0.3"
incoming = "0.1"
