[package]
name = "kvstore"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

[features]
default = []
bin = ["tracing-subscriber", "tracing-timing", "structopt", "tokio/macros", "tokio/rt-threaded"]

[dependencies]
bertha = { path = "../bertha" }
burrito-shard-ctl = { path = "../burrito-shard-ctl" }
color-eyre = "0.5"
futures-util = "0.3"
hashbrown = "0.7"
rand = "0.7"
serde  = { version = "1", features = ["derive"]}
tower-buffer = "0.3"
tower-service = "0.3"
tokio = {version = "0.2", features = ["rt-core", "sync"]}
tracing = "0.1"
tracing-futures = "0.2"
tracing-error = "0.1"
structopt = { version = "0.3", optional = true }
tracing-subscriber = { version = "0.2", optional = true }
tracing-timing  = { version = "0.4", optional = true }

[dev-dependencies]
test-util = { path = "../test-util" }
tracing-subscriber = "0.2"
bincode = "1"

[[bin]]
name = "kvserver"
required-features = ["bin"]
