[package]
name = "xdp-shard"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["ebpf"]
ebpf = []
bin = ["color-eyre", "ctrlc", "structopt", "tracing-subscriber"]

[dependencies]
eyre = "0.6"
nix = "0.17"
tracing = "0.1"
tracing-subscriber = { version = "0.2", optional = true }
color-eyre = { version = "0.5", optional = true }
ctrlc = { version = "3", optional = true }
structopt = { version = "0.3", optional = true }

[dev-dependencies]
bincode = "1"
criterion = "0.3"
ctrlc = "3"
rand = "0.7"
rand_distr = "0.2"
serde = { version = "1", features = ["derive"] }
structopt = "0.3"
tokio = { version = "0.3", features = ["rt", "rt-multi-thread", "macros", "sync", "net", "time"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"

[build-dependencies]
bindgen = "0.53"

[[bin]]
name = "dump_stats"
required-features = ["ebpf", "bin"]

[[bin]]
name = "xdp_clear"
required-features = ["ebpf", "bin"]

[[example]]
name = "shard"
required-features = ["ebpf", "bin"]
