[package]
name = "xdp-shard"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["ebpf"]
ebpf = []

[dependencies]
bincode = "1"
ctrlc = "3"
nix = "0.17"
structopt = "0.3"
tracing = "0.1"
tracing-subscriber = "0.2"

[dev-dependencies]
rpcbench = { path = "../rpcbench" }
tokio = { version = "0.2", features = ["rt-threaded", "macros", "sync"] }

[build-dependencies]
bindgen = "0.53"

[[bin]]
name = "dump_stats"
required-features = ["ebpf"]

[[bin]]
name = "xdp_clear"
required-features = ["ebpf"]

[[example]]
name = "shard"
required-features = ["ebpf"]
